# Generated by Django 5.2.11 on 2026-03-02 21:57

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_rename_service_servicemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='caption2',
            field=models.CharField(max_length=200, verbose_name='Altyazı2'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=cloudinary.models.CloudinaryField(help_text='Ölçü: 1920x570', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
